### PR TITLE
improved GeneratedFindOptions typing

### PR DESCRIPTION
**Pull request by SohaibSEG**
improved for better compatibility with scenarios where pagination and order are optional

### CODE REVIEW

**Comment by Valerionn** [comment]
Hello! Thank you for the PR - may I ask you why you need this change / what's the improvement with these changes? It's possible to change `skip: number | undefined`/`take: number | undefined` to `skip?: number`/`take?: number` without problems (though I do not know why that's better in this case since the type is generated by the package anyway).

But why do you want to make `orderBy` optional? It's always set by the `FilterParser` (though it may be an empty array if there is no `orderBy`), therefore I don't see the advantage you get by making it optional? But I'm always happy to change my opinion if you can give me an example where this is an improvement.

**Comment by SohaibSEG** [comment]
for example when you want to fetch all the records without any pagination or ordering 
the current typing requires you to explicitly pass 
```
take : undefined 
```
which in my case adds redundant code that is repeated across my services in endpoints that need filtering but not pagination

**Comment by Valerionn** [comment]
I'm sorry, but I still don't quite understand what's the problem in this case. If you type your service functions as described in the [documentation](https://github.com/chax-at/prisma-filter?tab=readme-ov-file#directfilterpipe), then they look like this (assuming a `Order` table in your DB):
```ts
  public async getOrders(findOptions: Prisma.OrderFindManyArgs) {
    // your code
  }
```

When you use the package to generate the find options in your controller, then you won't have to manually set anything like a `take: undefined`:
```ts
  @Get()
  public async getOrders(
    @Query(new DirectFilterPipe<any, Prisma.OrderWhereInput>(
      ['id', 'status', 'createdAt', 'refundStatus', 'refundedPrice', 'paymentDate', 'totalPrice', 'paymentMethod'],
      ['event.title', 'user.email', 'user.firstname', 'user.lastname', 'contactAddress.firstName', 'contactAddress.lastName'],
    )) filterDto: FilterDto<Prisma.OrderWhereInput>,
  ) {
    return this.someService.getOrders(filterDto.findOptions);
  }
```

If you want to call the service function manually, then you only have to match the `Prisma.OrderFindManyArgs`, therefore something like this:
```ts
return this.someService.getOrders({
  where: {
    userId: 17,
  },
  // no take etc. is required here
});
```

The only place in which the `GeneratedFindOptions` is used is `filterDto.findOptions` which is generated by the `DirectFilterPipe`. But I don't see how/where you would use this type as a constraint in which you have to set anything manually. Do you have an example of your code where you need this?

**Comment by SohaibSEG** [comment]
In my use case, 
I have two tables : Card and Client with Client 1:N Card relationship. both can be soft deleted si i wrote this wrapper method in the card service :
```typescript
private async findManyCards(
    findOptions: GeneratedFindOptions<Prisma.Fidelity_cardWhereInput>,
  ) {
    return this.prismaService.Card.findMany({
      where: {
        ...(findOptions.where || {}),
        deletedAt: null,
        Client: {
          AND: {
            ...(findOptions.where?.Client || {}),
            deletedAt: null,
          },
        },
      },
      include: { Client: true },
      orderBy: findOptions.orderBy,
      skip: findOptions.skip,
      take: findOptions.take,
    });
  }
```
I have another method that fetchs cards for a specific client. clients don't have too many cards so there is no need to paginate or order them. But there is a need for filtering, for example a client would want to list only cards which are active.
Before my modification my code would need to look like this :
```typescript
async findCardsByClientId(client_id : number, findOptions? : GeneratedFindOptions<Prisma.Fidelity_cardWhereInput>){
        return this.findManyCards({
                      where: {
                                ...(findOptions?.where || {}),
                                client_id: clientId,
                         },
                       orderBy: [],    // Must pass empty array
                       skip: undefined, // Must explicitly pass undefined
                       take: undefined, // Must explicitly pass undefined
                   });
}
```
But this repeated across many other methods in other services that use similar logic.
What I see convenient: 
```typescript
return this.findManyCards({
  where: {
    ...(findOptions?.where || {}),
    client_id: clientId,
  },
  // Cleaner: No need for redundant properties
});

```

**Comment by Valerionn** [comment]
You should be able to use Prisma's type directly instead of `GeneratedFindOptions`, like this:
```ts
private async findManyCards(
    findOptions: Prisma.Fidelity_cardFindManyArgs, // <- use FindManyArgs here
  ) {
    return this.prismaService.Card.findMany({
      where: {
        ...(findOptions.where || {}),
        deletedAt: null,
        Client: {
          AND: {
            ...(findOptions.where?.Client || {}),
            deletedAt: null,
          },
        },
      },
      include: { Client: true },
      orderBy: findOptions.orderBy,
      skip: findOptions.skip,
      take: findOptions.take,
    });
  }
```

This should still allow you to pass the findOptions from this package, but also allows you to call

```ts
        return this.findManyCards({
                      where: {
                                ...(findOptions?.where || {}),
                                client_id: clientId,
                         },
                   });
```

Alternatively, you can narrow the type down to something like this:
```ts
private async findManyCards(
    findOptions: Pick<Prisma.Fidelity_cardFindManyArgs, 'where' | 'orderBy' | 'skip' | 'take'>,
  ) {
```
so that the type is limited to the keys you're interested in.

The `GeneratedFindOptions` type is intended to represent the result of the filter transformation from this package. If you want to pass findOptions to somewhere, it's generally better to use Prisma's types (which directly represent the allowed parameters instead of representing the result of a filter transformation). You can pass every `GeneratedFindOptions` to Prisma's `FindManyArgs` (because it's a defined subset), but not the other way around.

**Comment by SohaibSEG** [comment]
Indeed, that is better way. thank you.

**Pull request closed without merging**
